language: C++

before_install: ./contrib/utilities/setup_travis.sh

os:
- linux
- mac

compiler: 
- clang
- gcc

script: ./contrib/utilities/run_travis.sh $CI_TEST_SUITE $CI_BUILD_TYPE

branches:
  only:
    - master

env:
#  This is way too long. We should find a way to do this in little pieces...
#  - CI_TEST_SUITE=tests 

#  These tests run ok, but they might be out of policy...
  - CI_TEST_SUITE=build CI_BUILD_TYPE=Debug
#  - CI_TEST_SUITE=build CI_BUILD_TYPE=Release

# These tests only compile and run "make tests"
#  - CI_TEST_SUITE=mini CI_BUILD_TYPE=Debug
#  - CI_TEST_SUITE=mini CI_BUILD_TYPE=Release
